#!/bin/bash

command=$(cat ~/.zsh_history | awk -F ';' '!seen[$2]++ {print $2}' | fzf --layout=reverse --no-sort --tac +s +m -1)

if [[ -n $command ]]; then
  echo "$command"
  read -p "Do you want to execute the command? (y/n): " choice

  if [[ $choice == "y" ]]; then
    eval "$command"
  else
    echo "Command not executed."
  fi
fi
