gui:
  showBottomLine: false
  showIcons: true
quitOnTopLevelReturn: true
notARepository: "quit"
disableStartupPopups: true
promptToReturnFromSubprocess: false
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
os:
  editCommandTemplate: '{{editor}}'
  editCommand: nvim --server /tmp/nvim-server-$(tmux display-message -p '#S').pipe --remote-send "<cmd>lua require('core.scripts.lazygit-open-file')('{{filename}}', '{{line}}')<CR>"
  openCommand: nvim --server /tmp/nvim-server-$(tmux display-message -p '#S').pipe --remote-send "<cmd>lua require('core.scripts.lazygit-open-file')('{{filename}}', '{{line}}')<CR>"
